---
- name: Add APT key
  become: true
  apt_key:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Repo
  become: true
  apt_repository:
    repo: 'deb
      https://pkg.cloudflare.com/
      {{ ansible_distribution_release }}
      main'
    state: present
    filename: cloudflare
  when: ansible_os_family == 'Debian'
