---
- name: Add pubkey.gpg
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.cloudflare.com/pubkey.gpg
    fingerprint: FBA8C0EE63617C5EED695C43254B391D8CACCBF8

- name: Install the repository rpm for EL7
  yum:
    name: http://pkg.cloudflare.com/cloudflare-release-latest.el7.rpm
    state: present
  when:
    - ansible_distribution_major_version == "7"

- name: Install the repository rpm for EL8
  yum:
    name: http://pkg.cloudflare.com/cloudflare-release-latest.el8.rpm
    state: present
  when:
    - ansible_distribution_major_version == "8"
